if (!require('dplyr')) install.packages ('dplyr')
if (!require('RSocrata')) install.packages ('RSocrata')
if (!require('tidyverse')) install.packages ('tidyverse')
if (!require('ggplot2')) install.packages ('ggplot2')
if (!require('readxl')) install.packages ('readxl')
if (!require('plyr')) install.packages('plyr')
if (!require('treemap')) install.packages('treemap')
if (!require('leaflet')) install.packages ('leaflet')
if (!require('forcats')) install.packages('forcats')
if (!require('ggExtra')) install.packages('ggExtra')
if (!require('GGally')) install.packages('GGally')